DEBUG 2022-05-17 17:44:45.116 UTC: 	 CRAB Client version: v3.220323
DEBUG 2022-05-17 17:44:45.116 UTC: 	 Running on: Linux lxplus7100.cern.ch 3.10.0-1160.59.1.el7.x86_64 #1 SMP Wed Feb 23 16:47:03 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux - CentOS Linux 7 (Core)
DEBUG 2022-05-17 17:44:45.116 UTC: 	 Executing command: 'status'
DEBUG 2022-05-17 17:44:45.117 UTC: 	 Found CRAB cache file /afs/cern.ch/user/s/sobhatta/.crab3
ERROR 2022-05-17 17:44:45.118 UTC: 	 Error: submit_stau250_mlsp1_ctau1000mm/crab_projects/crab_SUS-RunIISummer20UL18GEN-stau250_lsp1_ctau100mm_v4 is not a valid CRAB project directory.
ERROR 2022-05-17 17:44:45.118 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.220323.01/bin/crab.py", line 159, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.220323.01/bin/crab.py", line 144, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.220323.01/lib/CRABClient/Commands/status.py", line 48, in __init__
    SubCommand.__init__(self, logger, cmdargs)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.220323.01/lib/CRABClient/Commands/SubCommand.py", line 275, in __init__
    SubCommand.validateOptions(self)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.220323.01/lib/CRABClient/Commands/SubCommand.py", line 642, in validateOptions
    raise ConfigurationException(msg)
ConfigurationException: [91mError[0m: submit_stau250_mlsp1_ctau1000mm/crab_projects/crab_SUS-RunIISummer20UL18GEN-stau250_lsp1_ctau100mm_v4 is not a valid CRAB project directory.
INFO 2022-05-17 17:44:45.243 UTC: 	 Log file is /afs/cern.ch/work/s/sobhatta/private/LongLivedStaus/LLSTauProduction/crab.log
